name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "*/5 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: dazden94/dazden94@main
        with:
          CREDLY_USER: nedzad-winter.774b6a80
